spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 136247

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zhh:
        taskmanager:
          mapper: debug

server:
  port: 9090
  servlet:
    context-path: /start
    multipart:
      enabled: true
      location: D:/StudyProgramPlus_Uploads/temp  # 指向刚刚创建的持久化目录
      max-file-size: 50MB                         # 顺便放宽单文件上传大小限制（可根据需求调整）
      max-request-size: 50MB                      # 放宽单次请求总大小限制